vich_uploader:
    db_driver: orm

    mappings:
        utilisateur_image:
            uri_prefix: /images/utilisateur_image
            upload_destination: '%kernel.project_dir%/public/images/utilisateur_image'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true